import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {createHash} from 'node:crypto';
import {checkProductReadiness} from './check-product-readiness.mjs';
const hash = b => createHash('sha256').update(b).digest('hex');
function fixture() { const root=fs.mkdtempSync(path.join(os.tmpdir(),'nisi-readiness-')); fs.mkdirSync(path.join(root,'evidence')); fs.writeFileSync(path.join(root,'package.json'),'fixture\n'); const receipts=[]; for(const lane of ['portable','native','windows','install','evaluation']) { const body=JSON.stringify({schema:'fixture-v1',status:'PASS_SCOPED',sourceManifest:{'package.json':hash(Buffer.from('fixture\n'))}}); const p=`evidence/${lane}.json`; fs.writeFileSync(path.join(root,p),body); receipts.push({id:lane,path:p,sha256:hash(Buffer.from(body))}); } return {root,receipts}; }
const input = (f, patch={}) => ({schemaVersion:'nisi-product-readiness-input/v1',receipts:f.receipts,sourcePins:[{path:'package.json',sha256:hash(Buffer.from('fixture\n'))}],featureInventory:{required:['workflow'],observed:['workflow']},gates:['portable','native','windows','install','evaluation'].map(lane=>({id:lane,lane,receiptId:lane})),...patch});
test('all explicitly bound clean gates produce scoped readiness',()=>{const f=fixture(); const r=checkProductReadiness(input(f),{root:f.root}); assert.equal(r.status,'PASS_SCOPED'); assert.equal(r.ready,true); assert.equal(r.authorizing,false);});
test('missing gate and stale source remain non-PASS',()=>{const f=fixture(); const r=checkProductReadiness(input(f,{gates:input(f).gates.slice(0,4)}),{root:f.root}); assert.notEqual(r.status,'PASS_SCOPED'); assert.equal(r.lanes.evaluation.status,'NOT_RUN'); fs.writeFileSync(path.join(f.root,'package.json'),'drift\n'); const d=checkProductReadiness(input(f),{root:f.root}); assert.notEqual(d.status,'PASS_SCOPED');});
test('malformed, missing, skipped and unsafe evidence never passes',()=>{const f=fixture(); fs.writeFileSync(path.join(f.root,'evidence/native.json'),'not json'); const i=input(f); i.receipts[1]={...i.receipts[1],sha256:hash(Buffer.from('not json'))}; i.gates[1]={id:'native',lane:'native',receiptId:'native'}; fs.unlinkSync(path.join(f.root,'evidence/windows.json')); const r=checkProductReadiness(i,{root:f.root}); assert.equal(r.lanes.native.status,'ERROR'); assert.equal(r.lanes.windows.status,'NOT_RUN'); const unsafe={...i,sourcePins:[{path:'../package.json',sha256:i.sourcePins[0].sha256}]}; assert.notEqual(checkProductReadiness(unsafe,{root:f.root}).status,'PASS_SCOPED');});
