import test from 'node:test';import assert from 'node:assert/strict';
import {createExecutionCoordinatorV1} from '../hosts/repository/execution-coordinator-v1.mjs';
const owner=(id,over={})=>{let state=over.initial??'IDLE',cancelled=0,settles=0;return{registration:{id,status:()=>over.status?over.status():state,settled:async()=>{settles++;if(over.settled)return over.settled();},cancel:()=>{cancelled++;if(over.cancel)return over.cancel();state=over.cancelState??'IDLE';}},set:v=>state=v,counts:()=>({cancelled,settles})};};
const make=(owners,bound=30)=>createExecutionCoordinatorV1({owners:owners.map(x=>x.registration),settleTimeoutMs:bound});
const frozen=(v,s=new Set())=>{if(!v||typeof v!=='object'||s.has(v))return;s.add(v);assert.equal(Object.isFrozen(v),true);for(const x of Object.values(v))frozen(x,s);};
function shape(r,status,reason){assert.deepEqual(Object.keys(r).sort(),['authorizing','reason','schemaVersion','snapshot','status'].sort());assert.equal(r.schemaVersion,'nisi-execution-coordinator/v1');assert.equal(r.status,status);assert.equal(r.reason,reason);assert.equal(r.authorizing,false);frozen(r);}

test('inspect is immutable non-authorizing state and invokes no cancellation or settlement',()=>{const a=owner('node',{initial:'IDLE'}),c=make([a]),r=c.inspect();shape(r,'SNAPSHOT',null);assert.equal(r.snapshot.state,'ON');assert.equal(r.snapshot.capacityReusable,false);assert.deepEqual(a.counts(),{cancelled:0,settles:0});});
test('OFF requires every registered owner settlement and terminal status',async()=>{const a=owner('node',{initial:'BUSY'}),b=owner('scheduled',{initial:'OFF',cancelState:'OFF'}),c=make([a,b]);const r=await c.requestOff();shape(r,'OFF',null);assert.equal(r.snapshot.capacityReusable,true);assert.deepEqual(a.counts(),{cancelled:1,settles:1});assert.deepEqual(b.counts(),{cancelled:1,settles:1});assert.deepEqual(r.snapshot.owners.map(x=>x.status),['IDLE','OFF']);});
test('only explicitly registered cancellation callbacks run once',async()=>{let unrelated=0;const a=owner('a'),b=owner('b'),c=make([a,b]);await c.requestOff();await c.recheck();assert.equal(unrelated,0);assert.equal(a.counts().cancelled,1);assert.equal(b.counts().cancelled,1);assert.equal(a.counts().settles,2);});
test('delayed settlement keeps the operation active and confirms OFF only after join',async()=>{let release;const a=owner('slow',{initial:'BUSY',settled:()=>new Promise(r=>release=()=>{a.set('IDLE');r();})}),c=make([a],100);let done=false;const p=c.requestOff().then(x=>{done=true;return x;});await new Promise(r=>setImmediate(r));assert.equal(done,false);shape(c.inspect(),'SNAPSHOT',null);assert.equal(c.inspect().snapshot.state,'STOPPING');release();shape(await p,'OFF',null);});
test('overlapping request and recheck refuse without invoking callbacks twice',async()=>{let release;const a=owner('slow',{settled:()=>new Promise(r=>release=r)}),c=make([a],100),first=c.requestOff();await new Promise(r=>setImmediate(r));const busy=await c.recheck();shape(busy,'REFUSED','COORDINATOR_BUSY');assert.equal(a.counts().cancelled,1);assert.equal(a.counts().settles,1);release();await first;});
test('timeout preserves unconfirmed capacity and same handles can later be rechecked',async()=>{let ready=false;const a=owner('lost',{initial:'BUSY',settled:()=>ready?(a.set('IDLE'),Promise.resolve()):new Promise(()=>{})}),c=make([a],5),first=await c.requestOff();shape(first,'UNCONFIRMED','DRAIN_UNCONFIRMED');assert.equal(first.snapshot.owners[0].settlement,'TIMEOUT');assert.equal(first.snapshot.capacityReusable,false);ready=true;const recovered=await c.recheck();shape(recovered,'OFF',null);assert.deepEqual(a.counts(),{cancelled:1,settles:2});});
test('settlement rejection remains unconfirmed and may recover on recheck',async()=>{let fail=true;const a=owner('error',{settled:()=>fail?Promise.reject(Error('x')):Promise.resolve()}),c=make([a]);shape(await c.requestOff(),'UNCONFIRMED','DRAIN_UNCONFIRMED');fail=false;shape(await c.recheck(),'OFF',null);assert.equal(a.counts().cancelled,1);});
test('QUARANTINED or BUSY after fulfilled settlement never releases capacity',async()=>{for(const state of ['BUSY','QUARANTINED']){const a=owner(state,{initial:state,cancelState:state}),r=await make([a]).requestOff();shape(r,'UNCONFIRMED','DRAIN_UNCONFIRMED');assert.equal(r.snapshot.capacityReusable,false);assert.equal(r.snapshot.owners[0].status,state);}});
test('malformed or throwing status is retained as unconfirmed without raw errors',async()=>{for(const status of [()=> 'ACTIVE',()=>{throw Error('PRIVATE');}]){const a=owner('bad',{status}),r=await make([a]).requestOff();shape(r,'UNCONFIRMED','DRAIN_UNCONFIRMED');assert.equal(r.snapshot.owners[0].status,null);assert.equal(r.snapshot.owners[0].error,'STATUS_UNCONFIRMED');assert.equal(JSON.stringify(r).includes('PRIVATE'),false);}});
test('cancellation errors do not fabricate OFF before settlement and status evidence',async()=>{const a=owner('cancel-error',{initial:'BUSY',cancel:()=>{throw Error('stop');},settled:()=>Promise.reject(Error('not joined'))}),r=await make([a]).requestOff();shape(r,'UNCONFIRMED','DRAIN_UNCONFIRMED');assert.equal(r.snapshot.capacityReusable,false);assert.equal(a.counts().cancelled,1);});
test('registration is exact, bounded, unique and getter-free',()=>{const good=owner('a').registration;for(const input of [{owners:[],settleTimeoutMs:1},{owners:[good,good],settleTimeoutMs:1},{owners:[{...good,extra:true}],settleTimeoutMs:1},{owners:[good],settleTimeoutMs:0}])assert.throws(()=>createExecutionCoordinatorV1(input));let touched=0;const poisoned=Object.defineProperty({owners:[good]},'settleTimeoutMs',{enumerable:true,get(){touched++;return 1;}});assert.throws(()=>createExecutionCoordinatorV1(poisoned));assert.equal(touched,0);});
test('owner callbacks cannot reenter and start another lifecycle operation',async()=>{let c,nested;const a=owner('reentrant',{cancel(){nested=c.requestOff();}});c=make([a]);shape(await c.requestOff(),'OFF',null);shape(await nested,'REFUSED','COORDINATOR_BUSY');assert.equal(a.counts().cancelled,1);});
