// Boundary evidence uses synthetic framed static reports, not native execution.
import test from 'node:test';import assert from 'node:assert/strict';
import {sha256Text,stableStringify} from '../workflow/contracts.mjs';
import {createRepositorySnapshot} from '../hosts/repository/snapshot-contract.mjs';
import {fixedProfile,KERNEL_ARTIFACT_CAP} from '../hosts/swift-verifier/protocol.mjs';
import {createNativeIncidentSourcePlanV1,readNativeIncidentSourceInputV1,isIssuedNativeIncidentSourcePlanV1} from '../hosts/repository/native-incident-source-v1.mjs';
import {createBoundaryNativeIncidentFixture,boundaryFiles} from './helpers/native-incident-source-fixture.mjs';
import {createPagedIncidentHostFixture} from './helpers/incident-review-fixture.mjs';

const H=(part,value)=>sha256Text(`nisi/native-incident-${part}/v1\0${stableStringify(value)}`);
const frozen=(value,seen=new Set())=>{if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);assert.equal(Object.isFrozen(value),true);for(const child of Object.values(value))frozen(child,seen);};
async function fixture(){const f=await createBoundaryNativeIncidentFixture(),preview=f.host.incidentPreview();return{...f,preview,rows:preview.rows.filter(r=>r.classification==='FAILURE_CANDIDATE')};}
const planFor=(f,path)=>{const row=f.rows.find(r=>{const p=f.host.nativeIncidentSourcePlan({rowId:r.rowId});return p.status==='SOURCE_BOUND'&&readNativeIncidentSourceInputV1({plan:p}).artifact.relativePath===path;});assert.ok(row,path);return f.host.nativeIncidentSourcePlan({rowId:row.rowId});};

test('empty source has an honest NONEMPTY failure and zero-byte untruncated input',async()=>{const f=await fixture(),plan=planFor(f,'sources/empty.txt'),input=readNativeIncidentSourceInputV1({plan});assert.equal(input.artifact.content,'');assert.equal(input.artifact.byteLength,0);assert.equal(plan.selection.artifactByteLength,0);assert.equal(input.priorReport.status,'FAIL');assert.deepEqual(input.priorReport.outcomes.map(x=>[x.id,x.status]),[['DET-001-NONEMPTY','FAIL'],['DET-002-UTF8','PASS'],['DET-003-REQUIRED-SECTIONS','FAIL']]);const child=f.collected.staticHistory[0].group.entries[input.binding.checkIndex];assert.equal(child.receipt.outputs.stdout.truncated,false);assert.equal(child.receipt.outputs.stdout.capturedBytes,child.receipt.outputs.stdout.observedBytes);});

test('multibyte UTF8 preserves exact characters, byte length and digest privately',async()=>{const f=await fixture(),plan=planFor(f,'sources/multibyte.txt'),input=readNativeIncidentSourceInputV1({plan}),original=boundaryFiles.find(x=>x.path==='sources/multibyte.txt');assert.equal(input.artifact.content,original.content);assert.equal(input.artifact.byteLength,Buffer.byteLength(original.content,'utf8'));assert.equal(input.artifact.sha256,sha256Text(original.content));assert.equal(plan.selection.artifactByteLength,input.artifact.byteLength);});

test('exactly one MiB is source-bound without truncation',async()=>{const f=await fixture(),plan=planFor(f,'sources/exact-cap.txt'),input=readNativeIncidentSourceInputV1({plan});assert.equal(input.artifact.byteLength,KERNEL_ARTIFACT_CAP);assert.equal(Buffer.byteLength(input.artifact.content),KERNEL_ARTIFACT_CAP);const child=f.collected.staticHistory[0].group.entries[input.binding.checkIndex];assert.equal(child.receipt.outputs.stdout.truncated,false);assert.equal(child.receipt.outputs.stderr.truncated,false);});

test('all fixed profiles retain exact closed native reconstruction settings',async()=>{const f=await fixture();for(const [path,id]of [['sources/invalid.json','nisi-json-structure-v1'],['sources/incomplete.md','nisi-markdown-sections-v1'],['sources/multibyte.txt','nisi-text-structure-v1']]){const input=readNativeIncidentSourceInputV1({plan:planFor(f,path)}),fixed=fixedProfile(id);assert.deepEqual({...input.profile,requiredSections:[...input.profile.requiredSections],allowedAdvisoryDimensions:[...input.profile.allowedAdvisoryDimensions]},{...fixed,requiredSections:[...fixed.requiredSections],allowedAdvisoryDimensions:[],modelParticipationRequired:false,maximumAdvisoryDimensions:0});assert.equal(input.profile.modelParticipationRequired,false);assert.equal(input.profile.maximumAdvisoryDimensions,0);assert.deepEqual([...input.profile.requiredSections],id==='nisi-markdown-sections-v1'?['Rollback','Testing']:[]);frozen(input.profile);}});

test('public plan recursively excludes raw content, relative paths, stdout and reports',async()=>{const f=await fixture();for(const row of f.rows){const plan=f.host.nativeIncidentSourcePlan({rowId:row.rowId}),wire=JSON.stringify(plan),input=readNativeIncidentSourceInputV1({plan});for(const secret of [input.artifact.content,input.artifact.relativePath,'stdoutHex','priorReport','outcomes'])if(secret!=='')assert.equal(wire.includes(secret),false,secret.slice(0,40));const keys=[];(function visit(v){if(!v||typeof v!=='object')return;for(const[k,x]of Object.entries(v)){keys.push(k);visit(x);}})(plan);for(const forbidden of ['content','relativePath','stdoutHex','priorReport'])assert.equal(keys.includes(forbidden),false);}});

test('private input arrays, transcript and nested objects are deeply immutable',async()=>{const f=await fixture(),input=readNativeIncidentSourceInputV1({plan:planFor(f,'sources/incomplete.md')});frozen(input);assert.throws(()=>input.profile.requiredSections.push('Injected'));assert.throws(()=>input.priorReport.outcomes[0].status='PASS');assert.throws(()=>input.binding.attempt=99);});

test('all three native source hashes independently match their canonical domains',async()=>{const f=await fixture(),plan=planFor(f,'sources/invalid.json'),input=readNativeIncidentSourceInputV1({plan});assert.equal(input.priorTranscriptSha256,H('prior-transcript',input.priorReport.outcomes));const {inputSha256,sourcePlanDigest,...body}=input;assert.equal(inputSha256,H('source-input',body));assert.equal(plan.selection.inputSha256,inputSha256);assert.equal(sourcePlanDigest,H('source-plan',plan.selection));assert.equal(plan.sourcePlanDigest,sourcePlanDigest);});

test('reordered serialized bundle and cross-run selection refuse',async()=>{const a=await fixture(),b=await createPagedIncidentHostFixture(),row=a.rows[0],reordered=structuredClone(a.collected.bundle);reordered.staticBundle.entries[0].group.entries.reverse();const r=createNativeIncidentSourcePlanV1({bundle:reordered,context:a.context,preview:a.preview,rowId:row.rowId});assert.equal(r.status,'REFUSED');assert.equal(r.reason,'INVALID_EVIDENCE');const cross=b.host.nativeIncidentSourcePlan({rowId:row.rowId});assert.equal(cross.status,'REFUSED');assert.equal(cross.reason,'ROW_MISSING');assert.equal(isIssuedNativeIncidentSourcePlanV1(cross),false);});

test('invalid input accessors are rejected without invocation',async()=>{const f=await fixture(),row=f.rows[0];for(const key of ['bundle','context','preview','rowId']){let touched=0;const input={bundle:f.collected.bundle,context:null,preview:f.preview,rowId:row.rowId};Object.defineProperty(input,key,{enumerable:true,get(){touched++;throw Error('POISON');}});const r=createNativeIncidentSourcePlanV1(input);assert.equal(r.status,'REFUSED');assert.equal(r.reason,'INVALID_INPUT');assert.equal(touched,0);}});

test('oversized source is refused by the repository snapshot boundary before an issued Swift plan exists',()=>{assert.throws(()=>createRepositorySnapshot({files:[{path:'too-large.txt',content:'x'.repeat(KERNEL_ARTIFACT_CAP+1)}]}),{code:'REPOSITORY_CONTENT_LIMIT'});});
