// Source-consistency oracles only. Synthetic adapter observations are not native
// execution, incident admission, independent verification, or learning evidence.
import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256Text,stableStringify} from '../workflow/contracts.mjs';
import {createRepositoryRunBundleV1} from '../receipts/repository-run-v1.mjs';
import {createRepositoryIncidentPreviewV1} from '../history/repository-incident-candidates-v1.mjs';
import {createNativeIncidentSourcePlanV1,readNativeIncidentSourceInputV1,isIssuedNativeIncidentSourcePlanV1} from '../hosts/repository/native-incident-source-v1.mjs';
import {combinedFixture} from './helpers/repository-run-fixture.mjs';
import {mixedStaticOperationalFixture} from './helpers/incident-candidate-fixture.mjs';
import {createIncidentHostFixture} from './helpers/incident-host-fixture.mjs';
import {createPagedIncidentHostFixture} from './helpers/incident-review-fixture.mjs';
import {issuedSwiftChecksV1} from '../hosts/swift-verifier/check-plan-v1.mjs';

const KEYS=['schemaVersion','status','reason','selection','sourcePlanDigest','rawContentIncluded','persistable','freshness','requiresSeparateAdmission','nativeRerun','executionVerified','learningEligible','authorizing'];
const SELECTION=['rowId','rowFingerprint','previewSha256','binding','source','profile','artifactByteLength','priorTranscriptSha256','inputSha256'];
const INPUT=['schemaVersion','rowId','rowFingerprint','previewSha256','binding','source','artifact','profile','priorReport','priorTranscriptSha256','inputSha256','sourcePlanDigest'];
const hex=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
function assertClosed(r,status,reason){assert.deepEqual(Object.keys(r).sort(),[...KEYS].sort());assert.equal(r.schemaVersion,'nisi-native-incident-source-plan/v1');assert.equal(r.status,status);assert.equal(r.reason,reason);assert.equal(r.rawContentIncluded,false);assert.equal(r.persistable,false);assert.equal(r.freshness,'ORIGINAL_SNAPSHOT_ONLY');assert.equal(r.requiresSeparateAdmission,true);assert.equal(r.nativeRerun,'NOT_RUN');assert.equal(r.executionVerified,false);assert.equal(r.learningEligible,false);assert.equal(r.authorizing,false);assert.equal(Object.isFrozen(r),true);}
async function projected(t,options={staticOnly:true}){const fixture=await combinedFixture(t,options),bundle=createRepositoryRunBundleV1(fixture.context),preview=createRepositoryIncidentPreviewV1({bundle,context:fixture.context});return{fixture,bundle,preview};}
const make=({bundle,fixture,preview},rowId)=>createNativeIncidentSourcePlanV1({bundle,context:fixture.context,preview,rowId});

test('original issued static failure binds exact source bytes without exposing them publicly',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'&&r.binding.stage==='staticChecks'),plan=make(p,row.rowId);assertClosed(plan,'SOURCE_BOUND',null);assert.equal(isIssuedNativeIncidentSourcePlanV1(plan),true);assert.deepEqual(Object.keys(plan.selection).sort(),[...SELECTION].sort());assert.equal(plan.selection.rowId,row.rowId);assert.equal(plan.selection.rowFingerprint,row.fingerprint);assert.equal(plan.selection.previewSha256,p.preview.sha256);assert.deepEqual(plan.selection.binding,row.binding);assert.deepEqual(plan.selection.source,row.source);assert.ok(hex(plan.sourcePlanDigest));assert.ok(hex(plan.selection.inputSha256));assert.ok(hex(plan.selection.priorTranscriptSha256));assert.equal(JSON.stringify(plan).includes('retryLimit'),false);assert.equal(JSON.stringify(plan).includes('Preserve zero retries'),false);});

test('private accessor returns the frozen exact failed artifact and prior native report',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),plan=make(p,row.rowId),input=readNativeIncidentSourceInputV1({plan}),sourcePlan=p.fixture.context.plans.find(x=>x.fingerprint===row.source.planFingerprint),check=issuedSwiftChecksV1(sourcePlan)[row.binding.checkIndex];assert.deepEqual(Object.keys(input).sort(),[...INPUT].sort());assert.equal(input.schemaVersion,'nisi-native-incident-source-input/v1');assert.equal(input.rowId,row.rowId);assert.equal(input.sourcePlanDigest,plan.sourcePlanDigest);assert.equal(input.inputSha256,plan.selection.inputSha256);assert.equal(input.priorTranscriptSha256,plan.selection.priorTranscriptSha256);assert.equal(input.artifact.relativePath,check.target.path);assert.equal(input.artifact.content,check.preparation.materialized.files.find(x=>x.path===check.target.path).content);assert.equal(input.artifact.sha256,row.subject.contentSha256);assert.equal(input.artifact.byteLength,Buffer.byteLength(input.artifact.content));assert.equal(sha256Text(input.artifact.content),input.artifact.sha256);assert.equal(input.profile.id,check.target.profileId);assert.equal(input.priorReport.status,'FAIL');assert.equal(Object.isFrozen(input),true);assert.equal(stableStringify(input.binding),stableStringify(row.binding));});

test('source plan identity and private input are stable for the same original inputs',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),a=make(p,row.rowId),b=make(p,row.rowId);assert.equal(a.sourcePlanDigest,b.sourcePlanDigest);assert.equal(a.selection.inputSha256,b.selection.inputSha256);assert.deepEqual(readNativeIncidentSourceInputV1({plan:a}),readNativeIncidentSourceInputV1({plan:b}));assert.notEqual(a,b);});

test('serialized or cloned plans never retain private source authority',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),plan=make(p,row.rowId);for(const value of [structuredClone(plan),JSON.parse(JSON.stringify(plan)),{...plan},null,{}]){assert.equal(isIssuedNativeIncidentSourcePlanV1(value),false);assert.throws(()=>readNativeIncidentSourceInputV1({plan:value}));}});

test('accessor input is exact and rejects getters before invoking them',async t=>{let touched=0;for(const value of [null,{}, {plan:null,extra:true},Object.defineProperty({},'plan',{enumerable:true,get(){touched++;throw Error('getter');}})])assert.throws(()=>readNativeIncidentSourceInputV1(value));assert.equal(touched,0);});

test('cloned preview is not source authority even when bytes and hashes match',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),r=createNativeIncidentSourcePlanV1({bundle:p.bundle,context:p.fixture.context,preview:structuredClone(p.preview),rowId:row.rowId});assertClosed(r,'REFUSED','INVALID_PREVIEW');assert.equal(r.selection,null);assert.equal(r.sourcePlanDigest,null);assert.equal(isIssuedNativeIncidentSourcePlanV1(r),false);assert.throws(()=>readNativeIncidentSourceInputV1({plan:r}),{code:'NATIVE_SOURCE_NOT_ISSUED'});});

test('a different original preview cannot be substituted across original contexts',async t=>{const a=await projected(t),b=await projected(t),row=a.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),r=createNativeIncidentSourcePlanV1({bundle:a.bundle,context:a.fixture.context,preview:b.preview,rowId:row.rowId});assertClosed(r,'REFUSED','PREVIEW_MISMATCH');assert.equal(r.selection,null);});

test('missing, partial, malformed and noncanonical row ids refuse without fallback selection',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE');for(const [rowId,reason]of [['0'.repeat(64),'ROW_MISSING'],[row.rowId.slice(0,63)+(row.rowId.at(-1)==='0'?'1':'0'),'ROW_MISSING'],[row.rowId.slice(0,8)+'0'.repeat(56),'ROW_MISSING'],[row.rowId.slice(0,63),'INVALID_INPUT'],['','INVALID_INPUT'],[null,'INVALID_INPUT']]){const r=createNativeIncidentSourcePlanV1({bundle:p.bundle,context:p.fixture.context,preview:p.preview,rowId});assertClosed(r,'REFUSED',reason);assert.equal(r.selection,null);}});

test('recorded static PASS is not a native incident source',async t=>{const p=await projected(t,{staticOnly:false}),row=p.preview.rows.find(r=>r.binding.stage==='staticChecks'&&r.classification==='PASS'),r=make(p,row.rowId);assertClosed(r,'REFUSED','ROW_NOT_FAILURE');});

test('recorded Node failure remains unsupported because no file transcript can be invented',async t=>{const p=await projected(t,{staticOnly:false}),row=p.preview.rows.find(r=>r.binding.stage==='tests'&&r.classification==='FAILURE_CANDIDATE'),r=make(p,row.rowId);assertClosed(r,'REFUSED','UNSUPPORTED_STAGE');assert.equal(r.selection,null);});

test('operational static failures are not reconstructed as deterministic incidents',async t=>{const fixture=await mixedStaticOperationalFixture(t),bundle=createRepositoryRunBundleV1(fixture.context),preview=createRepositoryIncidentPreviewV1({bundle,context:fixture.context}),row=preview.rows.find(r=>r.binding.stage==='staticChecks'&&r.classification==='OPERATIONAL'),r=createNativeIncidentSourcePlanV1({bundle,context:fixture.context,preview,rowId:row.rowId});assertClosed(r,'REFUSED','ROW_NOT_FAILURE');});

test('interrupted evidence cannot become a source-bound native incident',async t=>{const p=await projected(t,{interrupt:'abort',staticOnly:false}),row=p.preview.rows.find(r=>r.classification==='INTERRUPTED'),r=make(p,row.rowId);assertClosed(r,'REFUSED',row.binding.stage==='tests'?'UNSUPPORTED_STAGE':'ROW_NOT_FAILURE');});

test('serialized bundle remains inspectable with original context, while cloned or cross-run context has no authority',async t=>{const a=await projected(t),b=await projected(t),row=a.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),serialized=createNativeIncidentSourcePlanV1({bundle:structuredClone(a.bundle),context:a.fixture.context,preview:a.preview,rowId:row.rowId});assertClosed(serialized,'SOURCE_BOUND',null);assert.equal(readNativeIncidentSourceInputV1({plan:serialized}).rowId,row.rowId);for(const context of [structuredClone(a.fixture.context),b.fixture.context]){const r=createNativeIncidentSourcePlanV1({bundle:a.bundle,context,preview:a.preview,rowId:row.rowId});assertClosed(r,'REFUSED','INVALID_EVIDENCE');assert.equal(isIssuedNativeIncidentSourcePlanV1(r),false);}});

test('a repaired run reconstructs the exact original failed attempt rather than the later passing source',async t=>{const p=await projected(t,{skipFirst:true,staticOnly:false}),row=p.preview.rows.find(r=>r.binding.stage==='staticChecks'&&r.binding.attempt===0&&r.classification==='FAILURE_CANDIDATE'),later=p.preview.rows.find(r=>r.binding.stage==='staticChecks'&&r.binding.checkIndex===row.binding.checkIndex&&r.binding.attempt===1),plan=make(p,row.rowId),input=readNativeIncidentSourceInputV1({plan}),originalPlan=p.fixture.context.plans.find(x=>x.fingerprint===row.source.planFingerprint),check=issuedSwiftChecksV1(originalPlan)[row.binding.checkIndex];assert.ok(later);assert.equal(later.classification,'PASS');assert.equal(plan.selection.binding.attempt,0);assert.equal(input.binding.attempt,0);assert.equal(input.source.planFingerprint,originalPlan.fingerprint);assert.equal(input.artifact.content,check.preparation.materialized.files.find(x=>x.path===check.target.path).content);assert.equal(input.artifact.sha256,row.subject.contentSha256);assert.notEqual(input.source.planFingerprint,later.source.planFingerprint);});

test('public selection metadata is copied and deeply frozen against later mutation',async t=>{const p=await projected(t),row=p.preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),plan=make(p,row.rowId),before=stableStringify(plan);assert.throws(()=>{plan.selection.binding.attempt=99;});assert.throws(()=>{plan.selection.source.receiptSha256='0'.repeat(64);});assert.ok(Object.isFrozen(plan.selection),'selection deep-frozen');assert.ok(Object.isFrozen(plan.selection.profile),'profile deep-frozen');assert.ok(Object.isFrozen(plan.selection.profile.allowedAdvisoryDimensions),'profile arrays deep-frozen');assert.notStrictEqual(plan.selection.binding,row.binding,'binding is a copy, not the preview object');assert.throws(()=>{plan.selection.rowId='0'.repeat(64);},TypeError,'rowId cannot be rewritten');assert.throws(()=>plan.selection.profile.allowedAdvisoryDimensions.push('x'),TypeError,'profile cannot be widened');assert.equal(stableStringify(plan),before);});

test('real settled host exposes source planning while unsettled host refuses',async t=>{const fresh=await createIncidentHostFixture(t),candidate=fresh.host.nativeIncidentSourcePlan({rowId:'0'.repeat(64)});assertClosed(candidate,'REFUSED','HOST_NOT_SETTLED');const {host,eligible}=await createPagedIncidentHostFixture(),row=eligible[0],plan=host.nativeIncidentSourcePlan({rowId:row.rowId});assertClosed(plan,'SOURCE_BOUND',null);assert.equal(plan.selection.rowId,row.rowId);assert.equal(readNativeIncidentSourceInputV1({plan}).artifact.sha256,row.subject.contentSha256);});

test('host method requires an exact full row-id request and never returns raw content',async()=>{const{host,eligible}=await createPagedIncidentHostFixture(),row=eligible[0];for(const input of [{rowId:row.rowId.slice(0,63)},{rowId:row.rowId,extra:true},null]){const r=host.nativeIncidentSourcePlan(input);assertClosed(r,'REFUSED','INVALID_INPUT');assert.equal(JSON.stringify(r).includes('failure-01'),false);}});
