// Original-issued repository metadata with synthetic process adapters and memfs.
// This is not native execution, authenticated consent, or root-cause evidence.
import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewRepositoryIncidentsV1} from '../hosts/history/review-repository-incidents-v1.mjs';
import {createIncidentHostFixture} from './helpers/incident-host-fixture.mjs';
import {openJournalOwner,recordJournalObservation} from '../history/journal-owner-v2.mjs';
import {memfs} from './journal-owner-v2.memfs.mjs';
import {assertDeepFrozen} from './journal-owner-v2.helper.mjs';
import {createPagedIncidentHostFixture} from './helpers/incident-review-fixture.mjs';

const RUN='/synthetic/repository-run',KEYS=['schemaVersion','status','reason','previewSha256','selectedRowId','ownerOpenAttempted','permitCallAttempted','captureCallAttempted','capture','cancelledAfterCaptureCall','permitReleaseStatus','learningEligible','authorizing'];
async function settled(t){const f=await createIncidentHostFixture(t);await f.host.run(f.options);await f.host.settled();const preview=f.host.incidentPreview(),row=preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE');assert.ok(row);return{...f,preview,row};}
const config=p=>({projectId:`task:${p}`,maxEntries:32,heartbeatTtlMs:30000,redactPaths:[]});
function base(host,extra={}){return{host,runDirectory:RUN,clock:()=>100,prompt:async()=>({kind:'answer',text:'no'}),openOwner:()=>({status:'REFUSED'}),signal:null,promptTimeoutMs:1000,...extra};}
function assertResult(r,status,reason){assert.deepEqual(Object.keys(r).sort(),[...KEYS].sort());assert.equal(r.schemaVersion,'nisi-repository-incident-review/v1');assert.equal(r.status,status);assert.equal(r.reason,reason);assert.equal(r.learningEligible,false);assert.equal(r.authorizing,false);assertDeepFrozen(r);}
function approving(row,preview,seen=[]){return async p=>{seen.push(p);assert.equal(Object.isFrozen(p),true);return{kind:'answer',text:seen.length===1?`SELECT ${row.rowId}`:`STORE ${row.fingerprint} ${preview.sha256}`};};}

test('actual host performs exact two-step selection and stores one metadata observation',async t=>{const{host,preview,row}=await settled(t),m=memfs(),seen=[];let opened;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:approving(row,preview,seen),openOwner:req=>{opened=req;return openJournalOwner({...req,fs:m.fs});}}));assertResult(r,'STORED',null);assert.equal(seen.length,2);assert.equal(r.previewSha256,preview.sha256);assert.equal(r.selectedRowId,row.rowId);assert.equal(r.ownerOpenAttempted,true);assert.equal(r.permitCallAttempted,true);assert.equal(r.captureCallAttempted,true);assert.equal(r.cancelledAfterCaptureCall,false);assert.equal(r.permitReleaseStatus,'CONSUMED');assert.equal(r.capture.rowId,row.rowId);assert.equal(opened.path,`${RUN}/incident-journal.jsonl`);assert.deepEqual({...opened.config},config(row.binding.taskFingerprint));assert.equal(opened.now,100);});

test('selection prompt shows only eligible rows and requires full row id',async t=>{const{host,preview,row}=await settled(t);let first;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async p=>{first=p;return{kind:'answer',text:`SELECT ${row.rowId.slice(0,20)}`};}}));assertResult(r,'NOT_STORED','SELECTION_MISMATCH');assert.match(first.text,/page 1/i);assert.match(first.text,new RegExp(row.rowId));assert.equal(typeof first.expectedAnswer,'string');assert.equal(first.expectedAnswer,`SELECT ${row.rowId}`);assert.equal(r.ownerOpenAttempted,false);assert.equal(JSON.stringify(first).includes('retry-settings.mjs'),false);assert.equal(preview.rows.filter(x=>x.classification!=='FAILURE_CANDIDATE').some(x=>first.text.includes(x.rowId)),false);});

test('old history approval and normalized incident approvals cannot store',async t=>{const{host,preview,row}=await settled(t);for(const answer of [`STORE ${preview.sha256}`,`select ${row.rowId}`,` SELECT ${row.rowId}`,`SELECT ${row.rowId} `]){let opens=0;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async()=>({kind:'answer',text:answer}),openOwner:()=>{opens++;}}));assert.equal(r.status,'NOT_STORED');assert.equal(opens,0);}});

test('second prompt binds row fingerprint plus preview digest and renders all warnings',async t=>{const{host,preview,row}=await settled(t);let n=0,second;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async p=>{if(++n===1)return{kind:'answer',text:`SELECT ${row.rowId}`};second=p;return{kind:'answer',text:'no'};}}));assertResult(r,'NOT_STORED','DECLINED');assert.match(second.text,new RegExp(row.fingerprint));assert.match(second.text,new RegExp(preview.sha256));for(const phrase of ['14','raw','linkable','authenticated','sweeper','erasure','learning','execution','publication'])assert.match(second.text,new RegExp(phrase,'i'));assert.equal(second.text.includes('retry-settings.mjs'),false);});

test('decline, EOF, no-TTY, signal, error and malformed prompt outcomes never open owner',async t=>{const{host}=await settled(t);for(const [answer,reason]of [[{kind:'answer',text:''},'DECLINED'],[{kind:'answer',text:'no'},'DECLINED'],[{kind:'answer',text:'n'},'DECLINED'],[{kind:'eof'},'EOF'],[{kind:'no-tty'},'NO_TTY'],[{kind:'signal'},'ABORTED'],[{kind:'error'},'PROMPT_ERROR'],[null,'PROMPT_ERROR']]){let opens=0;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async()=>answer,openOwner:()=>{opens++;}}));assertResult(r,'NOT_STORED',reason);assert.equal(opens,0);}});

test('hanging prompt is bounded by the overall timeout and aborts its owned signal',async t=>{const{host}=await settled(t);let inner,opens=0;const r=await reviewRepositoryIncidentsV1(base(host,{promptTimeoutMs:5,prompt:p=>{inner=p.signal;return new Promise(()=>{});},openOwner:()=>{opens++;}}));assertResult(r,'NOT_STORED','TIMEOUT');assert.equal(opens,0);assert.equal(Object.getOwnPropertyDescriptor(AbortSignal.prototype,'aborted').get.call(inner),true);});

test('same-host overlap is busy and guard releases after completion',async t=>{const{host}=await settled(t);let release;const wait=new Promise(r=>release=r),first=reviewRepositoryIncidentsV1(base(host,{prompt:()=>wait}));await new Promise(r=>setImmediate(r));const busy=await reviewRepositoryIncidentsV1(base(host));assertResult(busy,'NOT_STORED','REVIEW_BUSY');release({kind:'answer',text:'no'});assertResult(await first,'NOT_STORED','DECLINED');assertResult(await reviewRepositoryIncidentsV1(base(host)),'NOT_STORED','DECLINED');});

test('genuine abort before and during prompt prevents owner open despite suppressed listeners',async t=>{const{host}=await settled(t),a=new AbortController();a.abort();let prompts=0,r=await reviewRepositoryIncidentsV1(base(host,{signal:a.signal,prompt:()=>{prompts++;}}));assertResult(r,'NOT_STORED','ABORTED');assert.equal(prompts,0);const b=new AbortController();b.signal.addEventListener('abort',e=>e.stopImmediatePropagation());r=await reviewRepositoryIncidentsV1(base(host,{signal:b.signal,prompt:async()=>{b.abort();return{kind:'answer',text:'no'};}}));assertResult(r,'NOT_STORED','ABORTED');assert.equal(r.ownerOpenAttempted,false);});

test('synthetic abort events and overridden signal instance members cannot forge cancellation',async t=>{const{host}=await settled(t),c=new AbortController();let touched=0;for(const k of ['aborted','reason','addEventListener','removeEventListener'])Object.defineProperty(c.signal,k,{get(){touched++;throw Error(k)}});c.signal.dispatchEvent(new Event('abort'));const r=await reviewRepositoryIncidentsV1(base(host,{signal:c.signal}));assertResult(r,'NOT_STORED','DECLINED');assert.equal(touched,0);});

test('preview identity change after selection refuses before owner open',async t=>{const{host,preview,row}=await settled(t);let n=0,opens=0;const wrapped={incidentPreview(){return n++<2?preview:structuredClone(preview);},createIncidentPermit:host.createIncidentPermit,captureIncident:host.captureIncident,revokeIncidentPermit:host.revokeIncidentPermit};const r=await reviewRepositoryIncidentsV1(base(wrapped,{prompt:approving(row,preview),openOwner:()=>{opens++;}}));assertResult(r,'NOT_STORED','PREVIEW_CHANGED');assert.equal(opens,0);});

test('one post-clock preview mismatch cannot be erased by a later recovered callback',async t=>{const{host,preview,row}=await settled(t);let afterClock=false,mismatch=true,opens=0;const wrapped={incidentPreview(){if(afterClock&&mismatch){mismatch=false;return structuredClone(preview);}return preview;},createIncidentPermit:host.createIncidentPermit,captureIncident:host.captureIncident,revokeIncidentPermit:host.revokeIncidentPermit};const r=await reviewRepositoryIncidentsV1(base(wrapped,{clock:()=>{afterClock=true;return 100;},prompt:approving(row,preview),openOwner:()=>{opens++;}}));assertResult(r,'NOT_STORED','PREVIEW_CHANGED');assert.equal(opens,0);assert.equal(r.ownerOpenAttempted,false);});

test('invalid wall clock refuses before owner and permit calls',async t=>{const{host,preview,row}=await settled(t);for(const clock of [()=>NaN,()=>-0,()=>{throw Error('clock');}]){const r=await reviewRepositoryIncidentsV1(base(host,{clock,prompt:approving(row,preview)}));assertResult(r,'NOT_STORED','INVALID_CLOCK');assert.equal(r.ownerOpenAttempted,false);assert.equal(r.permitCallAttempted,false);}});

test('cancellation after permit creation revokes the private handle before capture',async t=>{const{host,preview,row}=await settled(t),m=memfs(),c=new AbortController();let revokeResult;const wrapped={incidentPreview:host.incidentPreview,createIncidentPermit(input){const p=host.createIncidentPermit(input);c.abort();return p;},captureIncident:host.captureIncident,revokeIncidentPermit(input){revokeResult=host.revokeIncidentPermit(input);return revokeResult;}};const r=await reviewRepositoryIncidentsV1(base(wrapped,{signal:c.signal,prompt:approving(row,preview),openOwner:req=>openJournalOwner({...req,fs:m.fs})}));assertResult(r,'NOT_STORED','ABORTED');assert.equal(r.permitCallAttempted,true);assert.equal(r.captureCallAttempted,false);assert.equal(r.permitReleaseStatus,'REVOKED');assert.equal(revokeResult.status,'REVOKED');});

test('invalid or thrown capture after call is uncertain and handle cleanup remains explicit',async t=>{const{host,preview,row}=await settled(t),m=memfs();for(const captureIncident of [()=>null,()=>{throw Error('PRIVATE');},()=>({status:'STORED'})]){let revokes=0;const wrapped={incidentPreview:host.incidentPreview,createIncidentPermit:host.createIncidentPermit,captureIncident,revokeIncidentPermit(input){revokes++;return host.revokeIncidentPermit(input);}};const r=await reviewRepositoryIncidentsV1(base(wrapped,{prompt:approving(row,preview),openOwner:req=>openJournalOwner({...req,fs:m.fs})}));assertResult(r,'UNCERTAIN','CAPTURE_UNCONFIRMED');assert.equal(r.captureCallAttempted,true);assert.equal(r.capture,null);assert.ok(revokes>0);assert.notEqual(r.permitReleaseStatus,'NOT_CREATED');}});

test('late cancellation preserves exact valid capture and reports consumed cleanup',async t=>{const{host,preview,row}=await settled(t),m=memfs(),c=new AbortController();let actual;const wrapped={incidentPreview:host.incidentPreview,createIncidentPermit:host.createIncidentPermit,captureIncident(input){actual=host.captureIncident(input);c.abort();return actual;},revokeIncidentPermit:host.revokeIncidentPermit};const r=await reviewRepositoryIncidentsV1(base(wrapped,{signal:c.signal,prompt:approving(row,preview),openOwner:req=>openJournalOwner({...req,fs:m.fs})}));assertResult(r,'STORED',null);assert.equal(r.capture,actual);assert.equal(r.cancelledAfterCaptureCall,true);assert.equal(r.permitReleaseStatus,'CONSUMED');});

test('genuine issued failure rows page without dropping candidates and select only from the displayed page',async()=>{const{host,preview,eligible}=await createPagedIncidentHostFixture();const seen=[];let call=0;const selected=eligible[10];const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async p=>{seen.push(p);return{kind:'answer',text:[`NEXT`,`PREV`,`PAGE 2`,`SELECT ${selected.rowId}`,'no'][call++]};}}));assertResult(r,'NOT_STORED','DECLINED');assert.equal(eligible.length>10,true);assert.equal(seen.length,5);assert.match(seen[0].text,/page 1/i);assert.match(seen[1].text,/page 2/i);assert.match(seen[2].text,/page 1/i);assert.match(seen[3].text,/page 2/i);assert.equal(seen[0].text.includes(selected.rowId),false);assert.equal(seen[1].text.includes(selected.rowId),true);assert.equal(r.selectedRowId,selected.rowId);assert.equal(r.ownerOpenAttempted,false);assert.equal(r.previewSha256,preview.sha256);});

test('out-of-range paging and the interaction cap refuse without opening the journal',async()=>{const{host}=await createPagedIncidentHostFixture();for(const [answer,reason] of [['PAGE 0','SELECTION_MISMATCH'],['PAGE 999','PAGE_INVALID'],['PREV','PAGE_INVALID']]){let opens=0;const r=await reviewRepositoryIncidentsV1(base(host,{prompt:async()=>({kind:'answer',text:answer}),openOwner:()=>{opens++;}}));assertResult(r,'NOT_STORED',reason);assert.equal(opens,0);}let calls=0,opens=0;const capped=await reviewRepositoryIncidentsV1(base(host,{prompt:async()=>{calls++;return{kind:'answer',text:calls%2?'NEXT':'PREV'};},openOwner:()=>{opens++;}}));assertResult(capped,'NOT_STORED','INTERACTION_LIMIT');assert.equal(calls,32);assert.equal(opens,0);});

test('a real owner sealed after permit yields the accepted consumed journal refusal',async t=>{const{host,preview,row}=await settled(t),m=memfs();let damaged=false;const fs={...m.fs,readFileSync(path){const bytes=m.fs.readFileSync(path);return damaged?Buffer.from('damaged'):bytes;},renameSync(a,b){m.fs.renameSync(a,b);damaged=true;}},projectId=`task:${row.binding.taskFingerprint}`,opened=openJournalOwner({path:`${RUN}/incident-journal.jsonl`,fs,config:config(row.binding.taskFingerprint),now:100});let permitResult;const wrapped={incidentPreview:host.incidentPreview,createIncidentPermit(input){permitResult=host.createIncidentPermit(input);recordJournalObservation({owner:opened.owner,entry:{id:'seal-entry',projectId,runId:'seal-run',attempt:0,candidateId:'seal-candidate',stage:'seal',receiptId:'seal-receipt',createdAt:100,ttlMs:1000,state:'FAILED',heartbeatAt:null,retryOf:null,revokes:null,payload:{}},now:100});return permitResult;},captureIncident:host.captureIncident,revokeIncidentPermit:host.revokeIncidentPermit};const r=await reviewRepositoryIncidentsV1(base(wrapped,{prompt:approving(row,preview),openOwner:()=>opened}));assertResult(r,'REFUSED','COMMIT_UNCERTAIN');assert.equal(r.captureCallAttempted,true);assert.equal(r.capture.recordAttempted,true);assert.equal(r.capture.consumed,true);assert.equal(r.capture.journal.status,'REFUSED');assert.equal(r.capture.journal.reason,'COMMIT_UNCERTAIN');assert.equal(r.permitReleaseStatus,'CONSUMED');});
