// Original-issued repository metadata with an in-memory journal filesystem.
// No native incident capture, root-cause proof, atomic CAS, or durability claim.
import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256Text,stableStringify} from '../workflow/contracts.mjs';
import {createRepositoryIncidentAccessV1,queryRepositoryIncidentV1} from '../history/repository-incident-capture-v1.mjs';
import {openJournalOwner,inspectJournalOwner} from '../history/journal-owner-v2.mjs';
import {createRunJournal} from '../history/run-journal-v1.mjs';
import {createIncidentHostFixture} from './helpers/incident-host-fixture.mjs';
import {memfs} from './journal-owner-v2.memfs.mjs';
import {assertDeepFrozen} from './journal-owner-v2.helper.mjs';

const PATH='/j/incidents.jsonl';
const H=(domain,value)=>sha256Text(domain+'\0'+stableStringify(value));
const permitKeys=['schemaVersion','status','reason','permit','declarationDigest','consumed','authorizing'];
const captureKeys=['schemaVersion','status','reason','entryId','rowId','declarationDigest','recordAttempted','consumed','journal','learningEligible','authorizing'];
const config=projectId=>({projectId,maxEntries:32,heartbeatTtlMs:30000,redactPaths:[]});
async function settled(t){const f=await createIncidentHostFixture(t);await f.host.run(f.options);await f.host.settled();const preview=f.host.incidentPreview(),row=preview.rows.find(r=>r.classification==='FAILURE_CANDIDATE');assert.ok(row);return{...f,preview,row};}
function declaration(preview,row,overrides={}){return{schemaVersion:'nisi-repository-incident-declaration/v1',declarationId:'incident-declaration-a',projectId:`task:${row.binding.taskFingerprint}`,rowId:row.rowId,rowFingerprint:row.fingerprint,previewSha256:preview.sha256,issuedAt:100,expiresAt:1000,createdAt:100,retentionMs:10000,consentClass:'WRITTEN_DECLARATION',destination:'LOCAL_INCIDENT_OBSERVATION_ONLY',rawContentPersisted:false,networkEgress:false,learningInfluence:false,...overrides};}
function opened(m,projectId,now=100,fs=m.fs){return openJournalOwner({path:PATH,fs,config:config(projectId),now});}
function assertPermit(r,status,reason){assert.deepEqual(Object.keys(r).sort(),[...permitKeys].sort());assert.equal(r.schemaVersion,'nisi-repository-incident-permit/v1');assert.equal(r.status,status);assert.equal(r.reason,reason);assert.equal(r.authorizing,false);assertDeepFrozen(r);}
function assertCapture(r,status,reason,attempted,consumed){assert.deepEqual(Object.keys(r).sort(),[...captureKeys].sort());assert.equal(r.schemaVersion,'nisi-repository-incident-capture/v1');assert.equal(r.status,status);assert.equal(r.reason,reason);assert.equal(r.recordAttempted,attempted);assert.equal(r.consumed,consumed);assert.equal(r.learningEligible,false);assert.equal(r.authorizing,false);assertDeepFrozen(r);}

test('actual host selects one issued failure row and stores exact metadata-only entry',async t=>{const{host,preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,owner=opened(m,projectId).owner,d=declaration(preview,row);const p=host.createIncidentPermit({owner,declaration:d,clock:()=>100});assertPermit(p,'CREATED',null);const r=host.captureIncident({permit:p.permit});assertCapture(r,'STORED',null,true,true);const id='ric1.'+H('nisi/repository-incident-entry-id/v1',{projectId,rowId:row.rowId});assert.equal(r.entryId,id);assert.equal(r.rowId,row.rowId);assert.equal(r.journal.entryId,id);const e=r.journal.snapshot.entries.find(x=>x.entry.id===id).entry;assert.equal(e.projectId,projectId);assert.equal(e.runId,row.binding.runId);assert.equal(e.attempt,row.binding.attempt);assert.equal(e.candidateId,`cand:${row.binding.candidateFingerprint}`);assert.equal(e.stage,'REPOSITORY_INCIDENT_CANDIDATE_V1');assert.equal(e.receiptId,`rcpt:${row.source.receiptSha256}`);assert.equal(e.state,'FAILED');assert.equal(stableStringify(e.payload.row),stableStringify(row));assert.notEqual(e.payload.row,row);assert.equal(e.payload.previewSha256,preview.sha256);for(const k of ['consentAuthenticityAttested','sourceAuthenticityAttested','executionAttested','nativeIncidentCaptured','learningEligible','authorizing'])assert.equal(e.payload[k],false);});

test('declaration is exact 15 fields and digest is independently canonical',async t=>{const{preview,row}=await settled(t),m=memfs(),d=declaration(preview,row),access=createRepositoryIncidentAccessV1({getPreview:()=>preview});assert.equal(Object.keys(d).length,15);const p=access.createPermit({owner:opened(m,d.projectId).owner,declaration:d,clock:()=>100});assertPermit(p,'CREATED',null);assert.equal(p.declarationDigest,H('nisi/repository-incident-declaration/v1',d));assert.equal(p.consumed,false);assert.ok(p.permit&&Object.isFrozen(p.permit));});

test('PASS selection and cloned preview/row cannot grant a permit',async t=>{const{preview}=await settled(t),m=memfs(),pass=preview.rows.find(r=>r.classification==='PASS'),original=createRepositoryIncidentAccessV1({getPreview:()=>preview}),owner=opened(m,`task:${pass.binding.taskFingerprint}`).owner,p=original.createPermit({owner,declaration:declaration(preview,pass),clock:()=>100});assertPermit(p,'REFUSED',p.reason);assert.equal(p.permit,null);const cloned=structuredClone(preview),row=cloned.rows.find(r=>r.classification==='FAILURE_CANDIDATE'),access=createRepositoryIncidentAccessV1({getPreview:()=>cloned});assertPermit(access.createPermit({owner,declaration:declaration(cloned,row),clock:()=>100}),'REFUSED','INVALID_PREVIEW');});

test('declaration selection and scope mismatches refuse without journal IO',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),owner=opened(m,`task:${row.binding.taskFingerprint}`).owner;for(const changes of [{rowId:'0'.repeat(64)},{rowFingerprint:'0'.repeat(64)},{previewSha256:'0'.repeat(64)},{projectId:'task:'+'0'.repeat(64)},{destination:'LOCAL_HISTORY'}]){const before=m.events.length,p=access.createPermit({owner,declaration:declaration(preview,row,changes),clock:()=>100});assertPermit(p,'REFUSED',p.reason);assert.equal(m.events.length,before);}});

test('handles are access-private and malformed calls never throw',async t=>{const{preview,row}=await settled(t),m=memfs(),a=createRepositoryIncidentAccessV1({getPreview:()=>preview}),b=createRepositoryIncidentAccessV1({getPreview:()=>preview}),p=a.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row),clock:()=>100});for(const fn of [()=>b.capture({permit:p.permit}),()=>b.revoke({permit:p.permit}),()=>a.capture(null),()=>a.revoke({})]){const r=fn();assert.equal(r.status,'REFUSED');assert.equal(r.authorizing,false);}});

test('clock rejection boundaries permanently revoke without record attempt',async t=>{const{preview,row}=await settled(t);for(const [now,reason,changes] of [[-0,'INVALID_CLOCK',{}],[99,'INVALID_CLOCK',{}],[1000,'PERMIT_EXPIRED',{}],[10101,'OBSERVATION_EXPIRED',{expiresAt:20000}]]){const m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),values=[100,now],p=access.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row,changes),clock:()=>values.length?values.shift():now});assert.equal(p.status,'CREATED');const before=m.events.length,r=access.capture({permit:p.permit});assertCapture(r,'REFUSED',reason,false,false);assert.equal(m.events.length,before);const again=access.capture({permit:p.permit});assertCapture(again,'REFUSED','PERMIT_REVOKED',false,false);}const m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),owner=opened(m,`task:${row.binding.taskFingerprint}`).owner,before=m.events.length,notYet=access.createPermit({owner,declaration:declaration(preview,row),clock:()=>99});assertPermit(notYet,'REFUSED','NOT_YET_VALID');assert.equal(notYet.permit,null);assert.equal(m.events.length,before);});

test('explicit revocation before capture wins and is idempotently visible',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),p=access.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row),clock:()=>100});const revoked=access.revoke({permit:p.permit});assertPermit(revoked,'REVOKED',null);assert.equal(revoked.consumed,false);assertCapture(access.capture({permit:p.permit}),'REFUSED','PERMIT_REVOKED',false,false);});

test('revocation during final clock prevents admission',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview});let p,calls=0;const clock=()=>{calls++;if(calls===3)access.revoke({permit:p.permit});return 100;};p=access.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row),clock});const before=m.events.length,r=access.capture({permit:p.permit});assertCapture(r,'REFUSED','PERMIT_REVOKED',false,false);assert.equal(m.events.length,before);});

test('two permits for one row allow only one admitted record attempt',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),owner=opened(m,`task:${row.binding.taskFingerprint}`).owner,p1=access.createPermit({owner,declaration:declaration(preview,row),clock:()=>100}),p2=access.createPermit({owner,declaration:declaration(preview,row,{declarationId:'incident-declaration-b'}),clock:()=>100});assert.equal(p1.status,'CREATED');assert.equal(p2.status,'CREATED');assertCapture(access.capture({permit:p1.permit}),'STORED',null,true,true);assertCapture(access.capture({permit:p2.permit}),'REFUSED','ROW_CONSUMED',false,true);});

test('journal project mismatch is an admitted consumed refusal',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),p=access.createPermit({owner:opened(m,'task:'+'0'.repeat(64)).owner,declaration:declaration(preview,row),clock:()=>100}),r=access.capture({permit:p.permit});assertCapture(r,'REFUSED','PROJECT',true,true);assert.equal(r.journal.status,'REFUSED');assertCapture(access.capture({permit:p.permit}),'REFUSED','PERMIT_CONSUMED',false,true);});

test('store IO failure remains consumed and is never retried automatically',async t=>{const{preview,row}=await settled(t),m=memfs({openSync:()=>Object.assign(Error('fail'),{code:'EIO'})}),access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),p=access.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row),clock:()=>100}),r=access.capture({permit:p.permit});assertCapture(r,'STORE_FAILED',r.reason,true,true);assertCapture(access.capture({permit:p.permit}),'REFUSED','PERMIT_CONSUMED',false,true);});

test('stale owners with different bytes produce consumed storage conflict, not an atomic-CAS claim',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,a=createRepositoryIncidentAccessV1({getPreview:()=>preview}),b=createRepositoryIncidentAccessV1({getPreview:()=>preview}),oa=opened(m,projectId).owner,ob=opened(m,projectId).owner,pa=a.createPermit({owner:oa,declaration:declaration(preview,row),clock:()=>100}),pb=b.createPermit({owner:ob,declaration:declaration(preview,row,{declarationId:'incident-stale-different'}),clock:()=>100});assert.equal(a.capture({permit:pa.permit}).status,'STORED');const r=b.capture({permit:pb.permit});assertCapture(r,'CONFLICT','CONFLICT',true,true);assert.equal(r.journal.status,'STORE_CONFLICT');});

test('identical NEW-owner replay truthfully reports verified UNCHANGED without durability',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,a=createRepositoryIncidentAccessV1({getPreview:()=>preview}),b=createRepositoryIncidentAccessV1({getPreview:()=>preview}),oa=opened(m,projectId).owner,ob=opened(m,projectId).owner,d=declaration(preview,row),pa=a.createPermit({owner:oa,declaration:d,clock:()=>100}),pb=b.createPermit({owner:ob,declaration:d,clock:()=>100});assert.equal(a.capture({permit:pa.permit}).status,'STORED');const same=b.capture({permit:pb.permit});assertCapture(same,'STORED',null,true,true);assert.equal(same.journal.status,'RECORDED');assert.equal(same.journal.store.status,'UNCHANGED');assert.equal(same.journal.store.verified,true);assert.equal(same.journal.store.durable,false);});

test('permit is consumed before filesystem record callback and post-admission revoke cannot mask result',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,access=createRepositoryIncidentAccessV1({getPreview:()=>preview});let permit,nested,revokeResult,entered=false;const fs={...m.fs,openSync(path,flags,mode){if(flags==='wx'&&!entered){entered=true;nested=access.capture({permit:permit.permit});revokeResult=access.revoke({permit:permit.permit});}return m.fs.openSync(path,flags,mode);}},owner=opened(m,projectId,100,fs).owner;permit=access.createPermit({owner,declaration:declaration(preview,row),clock:()=>100});const outer=access.capture({permit:permit.permit});assertCapture(nested,'REFUSED','PERMIT_CONSUMED',false,true);assertPermit(revokeResult,'REFUSED','PERMIT_CONSUMED');assertCapture(outer,'STORED',null,true,true);});

test('post-rename readback failure is uncertain and seals the owner',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,fs={...m.fs,renameSync(a,b){m.fs.renameSync(a,b);m.seed(b,Buffer.from('damaged'));}},access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),owner=opened(m,projectId,100,fs).owner,p=access.createPermit({owner,declaration:declaration(preview,row),clock:()=>100}),r=access.capture({permit:p.permit});assertCapture(r,'UNCERTAIN','READBACK_MISMATCH',true,true);assert.equal(inspectJournalOwner({owner}).snapshot.state,'COMMIT_UNCERTAIN');});

test('reentrant capture during clock is busy; outer call remains the sole attempt',async t=>{const{preview,row}=await settled(t),m=memfs(),access=createRepositoryIncidentAccessV1({getPreview:()=>preview});let p,n=0,nested;const clock=()=>{if(++n===2)nested=access.capture({permit:p.permit});return 100;};p=access.createPermit({owner:opened(m,`task:${row.binding.taskFingerprint}`).owner,declaration:declaration(preview,row),clock});const outer=access.capture({permit:p.permit});assertCapture(nested,'REFUSED','PERMIT_BUSY',false,false);assertCapture(outer,'STORED',null,true,true);});

test('independent access exact replay is duplicate; changed declaration conflicts under stable entry ID',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,d=declaration(preview,row),a=createRepositoryIncidentAccessV1({getPreview:()=>preview}),oa=opened(m,projectId).owner,pa=a.createPermit({owner:oa,declaration:d,clock:()=>100}),first=a.capture({permit:pa.permit});assert.equal(first.status,'STORED');const b=createRepositoryIncidentAccessV1({getPreview:()=>preview}),ob=opened(m,projectId).owner,pb=b.createPermit({owner:ob,declaration:d,clock:()=>100}),same=b.capture({permit:pb.permit});assertCapture(same,'DUPLICATE',null,true,true);assert.equal(same.entryId,first.entryId);const c=createRepositoryIncidentAccessV1({getPreview:()=>preview}),oc=opened(m,projectId).owner,pc=c.createPermit({owner:oc,declaration:declaration(preview,row,{declarationId:'incident-declaration-changed'}),clock:()=>100}),changed=c.capture({permit:pc.permit});assertCapture(changed,'CONFLICT','ID_CONTENT_MISMATCH',true,true);assert.equal(changed.entryId,first.entryId);});

test('fresh query reopens disk and returns only persisted unauthenticated observation',async t=>{const{preview,row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,access=createRepositoryIncidentAccessV1({getPreview:()=>preview}),p=access.createPermit({owner:opened(m,projectId).owner,declaration:declaration(preview,row),clock:()=>100}),stored=access.capture({permit:p.permit}),q=queryRepositoryIncidentV1({path:PATH,fs:m.fs,config:config(projectId),entryId:stored.entryId,now:100});assert.equal(q.status,'AVAILABLE_OBSERVATION');assert.equal(q.reason,null);assert.equal(q.entryId,stored.entryId);assert.equal(q.sourceTrust,'PERSISTED_UNAUTHENTICATED_OBSERVATION');assert.equal(q.learningEligible,false);assert.equal(q.authorizing,false);assert.equal(q.observation.row.rowId,row.rowId);assertDeepFrozen(q);});

test('fresh query reports missing and refuses corrupt or wrong-project stores without leakage',async t=>{const{row}=await settled(t),m=memfs(),projectId=`task:${row.binding.taskFingerprint}`,empty=createRunJournal(config(projectId));m.seed(PATH,Buffer.from(empty.serialize()));const missing=queryRepositoryIncidentV1({path:PATH,fs:m.fs,config:config(projectId),entryId:'ric1.'+'0'.repeat(64),now:100});assert.equal(missing.status,'MISSING');assert.equal(missing.observation,null);m.seed(PATH,Buffer.from('not a journal'));for(const cfg of [config(projectId),config('task:'+'0'.repeat(64))]){const q=queryRepositoryIncidentV1({path:PATH,fs:m.fs,config:cfg,entryId:'ric1.'+'0'.repeat(64),now:100});assert.equal(q.status,'REFUSED');assert.equal(q.observation,null);assert.equal(JSON.stringify(q).includes('not a journal'),false);}});
