import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {promptRepositoryHistoryV1} from '../hosts/history/terminal-history-prompt-v1.mjs';

class Input extends EventEmitter { constructor({tty=true,paused=true}={}){super();this.isTTY=tty;this.paused=paused;this.readableFlowing=!paused;this.encoding=null;}isPaused(){return this.paused;}resume(){this.paused=false;this.readableFlowing=true;return this;}pause(){this.paused=true;this.readableFlowing=false;return this;}setEncoding(x){this.encoding=x;return this;} }
class Output extends EventEmitter { constructor(tty=true){super();this.isTTY=tty;this.writes=[];}write(x){this.writes.push(x);return true;} }
const call=(input,output,extra={})=>promptRepositoryHistoryV1({text:'Review?\n',expectedAnswer:'STORE abc',signal:null,timeoutMs:100,input,output,...extra});
const later=fn=>queueMicrotask(fn);

test('non-TTY returns without writes, resume, or listeners',async()=>{for(const [i,o] of [[new Input({tty:false}),new Output()],[new Input(),new Output(false)]]){const r=await call(i,o);assert.deepEqual(r,{kind:'no-tty'});assert.equal(o.writes.length,0);assert.equal(i.listenerCount('data')+i.listenerCount('end')+i.listenerCount('error'),0);assert.equal(i.paused,true);}});
test('LF and CRLF delimiters alone are removed and whitespace remains raw',async()=>{for(const [wire,want] of [['STORE abc\n','STORE abc'],[' STORE abc \r\n',' STORE abc ']]){const i=new Input(),o=new Output();later(()=>i.emit('data',wire));assert.deepEqual(await call(i,o),{kind:'answer',text:want});assert.deepEqual(o.writes,['Review?\n']);assert.equal(i.paused,true);}});
test('fragmented UTF-8 input is assembled by byte length',async()=>{const i=new Input(),o=new Output();later(()=>{i.emit('data','ST');i.emit('data','ORE abc\n');});assert.deepEqual(await call(i,o),{kind:'answer',text:'STORE abc'});});
test('EOF before a line returns eof and cleans listeners',async()=>{const i=new Input(),o=new Output();later(()=>i.emit('end'));assert.deepEqual(await call(i,o),{kind:'eof'});assert.equal(i.eventNames().length,0);assert.equal(i.paused,true);});
test('input and output errors return error without throwing details',async()=>{for(const side of ['input','output']){const i=new Input(),o=new Output();later(()=> (side==='input'?i:o).emit('error',Error('secret')));assert.deepEqual(await call(i,o),{kind:'error'});assert.equal(i.paused,true);}});
test('timeout returns timeout, removes listeners, and restores prior paused state',async()=>{const i=new Input(),o=new Output();assert.deepEqual(await call(i,o,{timeoutMs:5}),{kind:'timeout'});assert.equal(i.eventNames().length,0);assert.equal(o.eventNames().length,0);assert.equal(i.paused,true);});
test('already-aborted and later native abort return signal with cleanup',async()=>{const a=new AbortController();a.abort();let i=new Input(),o=new Output();assert.deepEqual(await call(i,o,{signal:a.signal}),{kind:'signal'});assert.equal(o.writes.length,0);const b=new AbortController();i=new Input();o=new Output();later(()=>b.abort());assert.deepEqual(await call(i,o,{signal:b.signal}),{kind:'signal'});assert.equal(i.paused,true);});
test('suppressed abort event still resolves from native state',async()=>{const c=new AbortController(),i=new Input(),o=new Output();c.signal.addEventListener('abort',e=>e.stopImmediatePropagation());later(()=>c.abort());assert.deepEqual(await call(i,o,{signal:c.signal}),{kind:'signal'});});
test('synthetic abort event does not cancel and overridden instance signal members are unused',async()=>{const c=new AbortController(),i=new Input(),o=new Output();let touched=0;for(const k of ['aborted','reason','addEventListener','removeEventListener'])Object.defineProperty(c.signal,k,{get(){touched++;throw Error(k)}});later(()=>{c.signal.dispatchEvent(new Event('abort'));i.emit('data','no\n');});assert.deepEqual(await call(i,o,{signal:c.signal}),{kind:'answer',text:'no'});assert.equal(touched,0);});
test('a stream initially flowing is not incorrectly paused after completion',async()=>{const i=new Input({paused:false}),o=new Output();later(()=>i.emit('data','no\n'));assert.deepEqual(await call(i,o),{kind:'answer',text:'no'});assert.equal(i.paused,false);});
test('overlong UTF-8 line is rejected and never returned as an answer',async()=>{const i=new Input(),o=new Output();later(()=>i.emit('data','é'.repeat(513)+'\n'));assert.deepEqual(await call(i,o),{kind:'error'});assert.equal(i.paused,true);});
test('multiple pasted lines are rejected and literal Ctrl-C is a signal outcome',async()=>{let i=new Input(),o=new Output();later(()=>i.emit('data','STORE abc\nignored\n'));assert.deepEqual(await call(i,o),{kind:'error'});assert.equal(i.paused,true);i=new Input();o=new Output();later(()=>i.emit('data','\u0003'));assert.deepEqual(await call(i,o),{kind:'signal'});assert.equal(i.paused,true);});

test('completion removes only owned listeners and preserves unrelated listeners',async()=>{const i=new Input(),o=new Output();const inputData=()=>{},inputError=()=>{},outputError=()=>{};i.on('data',inputData);i.on('error',inputError);o.on('error',outputError);later(()=>i.emit('data','no\n'));assert.deepEqual(await call(i,o),{kind:'answer',text:'no'});assert.equal(i.listeners('data').includes(inputData),true);assert.equal(i.listeners('error').includes(inputError),true);assert.equal(o.listeners('error').includes(outputError),true);assert.equal(i.listenerCount('data'),1);assert.equal(i.listenerCount('error'),1);assert.equal(o.listenerCount('error'),1);});

test('fragmented multibyte Buffer input is decoded as one valid raw UTF-8 answer',async()=>{const i=new Input(),o=new Output(),wire=Buffer.from('STORÉ abc\n','utf8'),split=wire.indexOf(0xc3)+1;later(()=>{i.emit('data',wire.subarray(0,split));i.emit('data',wire.subarray(split));});assert.deepEqual(await call(i,o),{kind:'answer',text:'STORÉ abc'});assert.equal(i.paused,true);});

test('fresh undecided stdin is released when this prompt starts its input flow',async()=>{const i=new Input({paused:false}),o=new Output();i.readableFlowing=null;later(()=>i.emit('data','no\n'));assert.deepEqual(await call(i,o),{kind:'answer',text:'no'});assert.equal(i.readableFlowing,false);assert.equal(i.isPaused(),true);assert.equal(i.listenerCount('data'),0);});
