// Bounded verification of explicit repository-incident selection, storage, and fresh query.
// Relocated mutants are test-only dependency substitutions; no native or provider process runs.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),priorName='.build/repository-incident-candidates-verification-9Hh64Z/verification.json';
const sourceName='history/repository-incident-capture-v1.mjs',projectorName='history/repository-incident-candidates-v1.mjs',hostName='hosts/repository/reviewed-workflow-v1.mjs';
const captureTest='tests/repository-incident-capture.test.mjs',queryTest='tests/repository-incident-query.test.mjs',boundaryTest='tests/repository-incident-boundaries.test.mjs',focusedTests=[captureTest,queryTest,boundaryTest];
const additions=[sourceName,captureTest,queryTest,boundaryTest,'work-orders/repository-incident-capture-v1/verify-real-disk.mjs','work-orders/repository-incident-capture-v1/verify-focused.mjs','work-orders/repository-incident-capture-v1/verify.mjs'];
const expected={[sourceName]:'6b0aaaf0b21dde32eca9301e73863c37bc2ac1bff63b14de7120c35e8968933c',[projectorName]:'618c32c09775b2931826c39f442e5c103463f9c11c877e483781850a7e1751f2',[hostName]:'3e1ef6c149a292292db18b8d11eaf445201ccc407a613e3b03817f8033f53358',[captureTest]:'267e8a006e22fd230cdd2402691a93e8a93a9824fdc45bae017e542b48738ac4',[queryTest]:'df2c7a5c89276653242e8dce07ee5a3555c22f530763aedd7bdebb7ae168f7a5',[boundaryTest]:'5dc5034e5deae3624631248623fe450135efe708679b896b7d5c251c93b7a723','work-orders/repository-incident-capture-v1/verify-real-disk.mjs':'571223ff12cb21506f9710a8bc4ae44946d136a75c8b81e4f1b68ea6c97e8faa','work-orders/repository-incident-capture-v1/verify-focused.mjs':'0e53c0cdf71d9a2cd77549cec464c198a48b303517fa14fcd4074920bff1cb24'};
const hash=v=>createHash('sha256').update(v).digest('hex'),bytes=n=>fs.readFileSync(path.join(root,n)),prior=JSON.parse(bytes(priorName));assert.equal(prior.status,'PASS_SCOPED');assert.equal(Object.keys(prior.after).length,260);
for(const[n,p]of Object.entries(prior.after))if(![projectorName,hostName].includes(n))assert.equal(hash(bytes(n)),p,n);assert.equal(Object.keys(prior.after).filter(n=>![projectorName,hostName].includes(n)).length,258);for(const[n,p]of Object.entries(expected))assert.equal(hash(bytes(n)),p,n);
const names=[...Object.keys(prior.after),...additions.filter(n=>!Object.hasOwn(prior.after,n))].sort();assert.equal(names.length,267);assert.equal(new Set(names).size,267);const pins=()=>Object.fromEntries(names.map(n=>[n,hash(bytes(n))])),before=pins(),evidence=fs.mkdtempSync(path.join(root,'.build/repository-incident-capture-verification-'));
const record={schemaVersion:1,status:'INCOMPLETE',startedAt:new Date().toISOString(),evidence,node:process.version,priorVerification:priorName,priorPinCount:260,unchangedPriorPins:258,intentionalPriorChanges:[projectorName,hostName],checkedFiles:267,before,focused:null,relocatedControl:null,variants:[],product:null,authorizing:false,scope:'Explicit metadata-only incident observation; no native incident, root-cause proof, atomic CAS, automatic erasure, learning, or release acceptance'};
function replaceOnce(s,o,n){assert.equal(s.split(o).length,2,'one target: '+o.slice(0,100));return s.replace(o,n);}function relocate(text,origin,dest){const resolve=s=>{const r=path.resolve(path.dirname(path.join(root,origin)),s),rel=path.relative(root,r);return pathToFileURL(dest[rel]??r).href;};return text.replace(/from '([^']+)'/g,(w,s)=>s.startsWith('.')?"from '"+resolve(s)+"'":w).replace(/import\('([^']+)'\)/g,(w,s)=>s.startsWith('.')?"import('"+resolve(s)+"')":w);}
function counters(out){return Object.fromEntries(['tests','pass','fail','cancelled','skipped','todo'].map(k=>{const m=[...out.matchAll(new RegExp('^(?:# |ℹ )'+k+' (\\d+)$','gm'))];assert.equal(m.length,1);return[k,Number(m[0][1])];}));}function execute(cmd,args,dir,timeout){const c=spawnSync(cmd,args,{cwd:root,encoding:'utf8',timeout,maxBuffer:16777216});fs.writeFileSync(path.join(dir,'stdout.txt'),c.stdout??'',{flag:'wx'});fs.writeFileSync(path.join(dir,'stderr.txt'),c.stderr??'',{flag:'wx'});assert.equal(c.error,undefined);assert.equal(c.signal,null);const x=counters(c.stdout);assert.equal(x.cancelled+x.skipped+x.todo,0);const codes=[...c.stdout.matchAll(/^\s+code: '([^']+)'$/gm)].map(m=>m[1]);assert.equal(codes.length,x.fail);const assertionFailures=codes.filter(v=>v==='ERR_ASSERTION').length;return{exitCode:c.status,...x,assertionFailures,nonAssertionFailures:codes.length-assertionFailures,failureCodes:Object.fromEntries([...new Set(codes)].sort().map(v=>[v,codes.filter(x=>x===v).length]))};}const passing=n=>({exitCode:0,tests:n,pass:n,fail:0,cancelled:0,skipped:0,todo:0,assertionFailures:0,nonAssertionFailures:0,failureCodes:{}});
const source=bytes(sourceName).toString('utf8'),variants=[
['bypass-preview-brand',s=>replaceOnce(s,"if (!isIssuedRepositoryIncidentPreviewV1(preview) || preview.status !== 'PREVIEW') fail('INVALID_PREVIEW');","if (preview?.status !== 'PREVIEW') fail('INVALID_PREVIEW');")],
['consume-after-record',s=>replaceOnce(s,"state.consumed = true; consumedRows.add(state.row.rowId); attempted = true;\n      const journal = recordJournalObservation({owner:state.owner,entry,now:final.now});","const journal = recordJournalObservation({owner:state.owner,entry,now:final.now});\n      state.consumed = true; consumedRows.add(state.row.rowId); attempted = true;")],
['omit-post-clock-revocation',s=>replaceOnce(s,"if (state.revoked) return {reason:'PERMIT_REVOKED'};\n  const d = state.declaration;","if (false) return {reason:'PERMIT_REVOKED'};\n  const d = state.declaration;")],
['entry-id-includes-row-content',s=>replaceOnce(s,"entryId:'ric1.' + H('entry-id',{projectId:d.projectId,rowId:row.rowId}),","entryId:'ric1.' + H('entry-id',{projectId:d.projectId,rowId:row.rowId,rowFingerprint:row.fingerprint}),")],
['query-caches-first-open',s=>replaceOnce(s,"const opened = openJournalOwner({path,fs,config,now});","const opened = queryRepositoryIncidentV1._cached ??= openJournalOwner({path,fs,config,now});")],
['expiry-allows-boundary',s=>replaceOnce(s,"else if (now >= d.expiresAt) reason = 'PERMIT_EXPIRED';","else if (now > d.expiresAt) reason = 'PERMIT_EXPIRED';")],
['ignore-row-fingerprint',s=>replaceOnce(s,"if (row.fingerprint !== d.rowFingerprint || 'task:' + row.binding.taskFingerprint !== d.projectId)","if ('task:' + row.binding.taskFingerprint !== d.projectId)")]];
function relocated(label,altered){const dir=path.join(evidence,label);fs.mkdirSync(dir);const sp=path.join(dir,path.basename(sourceName)),dest={[sourceName]:sp};fs.writeFileSync(sp,relocate(altered,sourceName,dest),{flag:'wx'});const paths=focusedTests.map(n=>{const p=path.join(dir,path.basename(n));let text=relocate(bytes(n).toString('utf8'),n,dest);if(n===boundaryTest)text=replaceOnce(text,"root=fileURLToPath(new URL('../',import.meta.url))","root="+JSON.stringify(root+path.sep));fs.writeFileSync(p,text,{flag:'wx'});return p;});return{canonicalSha256:hash(source),semanticSha256:hash(altered),...execute(process.execPath,['--test','--test-reporter=tap',...paths],dir,20000)};}
try{const d=path.join(evidence,'focused');fs.mkdirSync(d);record.focused=execute(process.execPath,['--test','--test-reporter=tap',...focusedTests],d,20000);assert.deepEqual(record.focused,passing(32));record.relocatedControl=relocated('relocated-control',source);assert.deepEqual(record.relocatedControl,{canonicalSha256:hash(source),semanticSha256:hash(source),...passing(32)});for(const[n,m]of variants){const x=relocated(n,m(source));record.variants.push({name:n,...x});assert.equal(x.tests,32);assert.equal(x.pass+x.fail,32);assert.equal(x.exitCode,1);assert.ok(x.assertionFailures>0,n+' runtime-only failure');}const pd=path.join(evidence,'product');fs.mkdirSync(pd);record.product=execute('npm',['run','check'],pd,120000);assert.equal(record.product.exitCode,0);assert.equal(record.product.pass,record.product.tests);assert.equal(record.product.fail,0);record.after=pins();record.changedDuringVerification=names.filter(n=>before[n]!==record.after[n]);assert.deepEqual(record.changedDuringVerification,[]);record.status='PASS_SCOPED';}catch(e){record.status='FAIL';record.failure=String(e?.message??e);process.exitCode=1;}finally{record.completedAt=new Date().toISOString();fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify(record,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:record.status,evidence,focused:record.focused,relocatedControl:record.relocatedControl,variants:record.variants,product:record.product,changedDuringVerification:record.changedDuringVerification??null,failure:record.failure??null}));}
